### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by CroniD** [leanix/leanix-reporting-cli#1]
Hi @psurrey ,

I'm getting an error (see below) after the generation of the initial demo project once I execute "npm start".

```
Uncaught ReferenceError: $ is not defined
    at Object.module.exports (VM529 report.6cb6038….js:9563)
    at __webpack_require__ (VM529 report.6cb6038….js:9248)
    at Object.<anonymous> (VM529 report.6cb6038….js:9581)
    at __webpack_require__ (VM529 report.6cb6038….js:9248)
    at ALL_MESSAGES_ID (VM529 report.6cb6038….js:9294)
    at Object.defineProperty.value (VM529 report.6cb6038….js:9297)
    at __webpack_require__ (VM529 report.6cb6038….js:20)
    at Object.installedModules (VM529 report.6cb6038….js:9212)
    at __webpack_require__ (VM529 report.6cb6038….js:20)
    at Object.<anonymous> (VM529 report.6cb6038….js:3663)
```

I excluded jquery in my package.json, but I think that error is more likely related to internal logic of leanix-reporting, but I'm not sure.

BTW: it worked yesterday with another project.

Best regards

**Comment by CroniD** [comment]
Hi there again,

looking at the @leanix/reporting npm package, you may missed declaring the dependencies of jquery and lodash in the package.json.

**Comment by psurrey** [comment]
Hi @CroniD ,

we have excluded jquery and lodash from the leanix-reporting library bundle. So they need to be loaded explicitly by the report itself. See https://github.com/leanix/leanix-reporting-cli/commit/c0621be846eb3023120f70990209995b3ed38d8a . I will create a new beta release tomorrow, that will include this fix.

I think the best way is to declare those dependencies within the @leanix/reporting npm package instead of the cli. That is the next step then.

Thanks for your help!

**Comment by CroniD** [comment]
Hi @psurrey ,

Thank you. Looking forward to that.


Best regards

**Comment by psurrey** [comment]
Hello @CroniD ,

I have released a new version of @leanix/reporting (see https://github.com/leanix/leanix-reporting/releases/tag/1.0.5). I will release the new version of the cli as soon as I have css bundling working.

Please update to @leanix/reporting version 1.0.5 in your projects and make sure the webpack configuration is updated, so that jquery and lodash are properly provided. See: https://github.com/leanix/leanix-reporting-cli/commit/c0621be846eb3023120f70990209995b3ed38d8a

We have to think about how we want to update existing webpack.config.js files with a new release of leanix-reporting-cli...

Looking forward to your feedback.

Best regards

**Comment by CroniD** [comment]
Hi @psurrey ,

thank you. I'll test these changes as soon as possible.

Regarding the webpack.config.js ... I don't know. I wouldn't bother. As a custom report developer you have to modify this file by yourself at some point. E.g. if one want to use React with JSX syntax, one has to add the babel-react-preset, or maybe a preset to use TypeScript. Merging an modified webpack.config.js might be really difficult for the reporting cli. So as long as you don't couple the reporting framework with the cli (meaning by hard dependencies), there should be no reason to take care. Well, the way I see it is that the cli is a starting point, not something one has to observe for updates. If one creates a new report, he works with the updated cli, but older reports should not need to in my optinion.


Best regards
